### ISSUE TITLE
Swapped const 1 and 2

### ISSUE THREAD

**Issue by theGiallo** [archer884/squirrel-rng#1]
https://github.com/archer884/squirrel-rng/blob/165bb1f2c035457ac4f82052c2db037e0a79f431/src/lib.rs#L56

Is there a reason why BIT_NOISE1 and BIT_NOISE2 values are swapped in your code, relatively to the talk in this slide https://youtu.be/LWFzPP8ZbdU?t=3117 ?

**Comment by archer884** [comment]
No, that’s probably just an error on my part.
